-- Equipment sort_id mapping
UPDATE equipment SET stats = stats || '{"sort_id": 100}'::jsonb WHERE name_en = 'Iron Katana' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 101}'::jsonb WHERE name_en = 'Cheese Knife' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 102}'::jsonb WHERE name_en = 'Bone Katana "Wolf"' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 103}'::jsonb WHERE name_en = 'Blood Cry' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 104}'::jsonb WHERE name_en = 'Wind Thief Scimitar' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 105}'::jsonb WHERE name_en = 'Arzuros Naginata' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 106}'::jsonb WHERE name_en = 'Frilled Slash' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 107}'::jsonb WHERE name_en = 'Hidden Saber' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 108}'::jsonb WHERE name_en = 'Khanga Edge' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 109}'::jsonb WHERE name_en = 'Daito Crow' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 110}'::jsonb WHERE name_en = 'Sinister Long Sword' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 111}'::jsonb WHERE name_en = 'Wyvern Blade "Verde"' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 112}'::jsonb WHERE name_en = 'Aknosom Sabre' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 113}'::jsonb WHERE name_en = 'Dios Katana' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 114}'::jsonb WHERE name_en = 'Wyvern Blade "Maple"' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 115}'::jsonb WHERE name_en = 'Drowning Shaft' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 116}'::jsonb WHERE name_en = 'Plesioth Splasher' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 117}'::jsonb WHERE name_en = 'Shogun Cutter' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 118}'::jsonb WHERE name_en = 'Almudron Blade' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 119}'::jsonb WHERE name_en = 'Kakaru Kumo Naki' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 120}'::jsonb WHERE name_en = 'Hydra Tornaria' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 121}'::jsonb WHERE name_en = 'Wailing Ghost' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 122}'::jsonb WHERE name_en = 'Spark Slicer' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 123}'::jsonb WHERE name_en = 'Wyvern Blade "Beryl"' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 124}'::jsonb WHERE name_en = 'Usurper''s Boltslicer' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 125}'::jsonb WHERE name_en = 'Rey Tonitrus' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 126}'::jsonb WHERE name_en = 'Blango Decimator' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 127}'::jsonb WHERE name_en = 'Glacial Shotel' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 128}'::jsonb WHERE name_en = 'Icebrink' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 129}'::jsonb WHERE name_en = 'Cawscythe' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 130}'::jsonb WHERE name_en = 'Reaver "Cruelty"' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 131}'::jsonb WHERE name_en = 'Veldian Ensis' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 132}'::jsonb WHERE name_en = 'Duke''s Sinclair' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 133}'::jsonb WHERE name_en = 'Azure Elder Long Sword' AND type = 'longsword';
UPDATE equipment SET stats = stats || '{"sort_id": 200}'::jsonb WHERE name_en = 'Bone Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 201}'::jsonb WHERE name_en = 'Venom Monster' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 202}'::jsonb WHERE name_en = 'Chata Clobberer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 203}'::jsonb WHERE name_en = 'Five-Pronged Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 204}'::jsonb WHERE name_en = 'Frilled Blow' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 205}'::jsonb WHERE name_en = 'Calamitous Portent' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 206}'::jsonb WHERE name_en = 'Kulu Beak' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 207}'::jsonb WHERE name_en = 'Cluster Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 208}'::jsonb WHERE name_en = 'Golm Gavel' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 209}'::jsonb WHERE name_en = 'Matraca Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 210}'::jsonb WHERE name_en = 'Diablos Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 211}'::jsonb WHERE name_en = 'Sinister Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 212}'::jsonb WHERE name_en = 'Gunhammer Prototype' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 213}'::jsonb WHERE name_en = 'Kut-Ku Pick' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 214}'::jsonb WHERE name_en = 'Dios Tailhammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 215}'::jsonb WHERE name_en = 'Rosenhammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 216}'::jsonb WHERE name_en = 'Shell Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 217}'::jsonb WHERE name_en = 'Scorching Isshata' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 218}'::jsonb WHERE name_en = 'Ludroth Splashhammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 219}'::jsonb WHERE name_en = 'Type 42 Shellbuster' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 220}'::jsonb WHERE name_en = 'Ceanataur Head Axe' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 221}'::jsonb WHERE name_en = 'Almudron Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 222}'::jsonb WHERE name_en = 'Plesioth Head' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 223}'::jsonb WHERE name_en = 'Bag o'' Horrors' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 224}'::jsonb WHERE name_en = 'Bleeding Bopper' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 225}'::jsonb WHERE name_en = 'Emerald Beater' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 226}'::jsonb WHERE name_en = 'Usurper''s Thunder' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 227}'::jsonb WHERE name_en = 'Vortex Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 228}'::jsonb WHERE name_en = 'Frozen Core' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 229}'::jsonb WHERE name_en = 'Conehead Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 230}'::jsonb WHERE name_en = 'Yeti Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 231}'::jsonb WHERE name_en = 'Hammer of Winter Moon' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 232}'::jsonb WHERE name_en = 'Graceful Death' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 233}'::jsonb WHERE name_en = 'Devil''s Due' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 234}'::jsonb WHERE name_en = 'Veldian Malleus' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 235}'::jsonb WHERE name_en = 'Duke Smiter' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 236}'::jsonb WHERE name_en = 'Azure Elder Hammer' AND type = 'hammer';
UPDATE equipment SET stats = stats || '{"sort_id": 300}'::jsonb WHERE name_en = 'Bone Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 301}'::jsonb WHERE name_en = 'Poisoned Capri' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 302}'::jsonb WHERE name_en = 'Lumu Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 303}'::jsonb WHERE name_en = 'Zurogong Primo' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 304}'::jsonb WHERE name_en = 'Kulu Duda' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 305}'::jsonb WHERE name_en = 'Sandpipe' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 306}'::jsonb WHERE name_en = 'Vicello Nulo Green' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 307}'::jsonb WHERE name_en = 'Golm Drum' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 308}'::jsonb WHERE name_en = 'Raven Shamisen' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 309}'::jsonb WHERE name_en = 'Striped Dragonga' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 310}'::jsonb WHERE name_en = 'Sinister Strum' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 311}'::jsonb WHERE name_en = 'Spirit Dragonwood Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 312}'::jsonb WHERE name_en = 'Kut-Ku''s Song' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 313}'::jsonb WHERE name_en = 'Vicello Nulo Red' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 314}'::jsonb WHERE name_en = 'Anjanath Hum' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 315}'::jsonb WHERE name_en = 'Sublime Bell' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 316}'::jsonb WHERE name_en = 'Ajara Reverberator' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 317}'::jsonb WHERE name_en = 'Rathalos Feroce' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 318}'::jsonb WHERE name_en = 'Magia Charm' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 319}'::jsonb WHERE name_en = 'Frog Flute' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 320}'::jsonb WHERE name_en = 'Type 63 Warmonica' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 321}'::jsonb WHERE name_en = 'Poetic Bell' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 322}'::jsonb WHERE name_en = 'Hydros Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 323}'::jsonb WHERE name_en = 'Vicello Nulo Yellow' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 324}'::jsonb WHERE name_en = 'Khezu Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 325}'::jsonb WHERE name_en = 'Blood Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 326}'::jsonb WHERE name_en = 'Emerald Flap' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 327}'::jsonb WHERE name_en = 'Fulguring Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 328}'::jsonb WHERE name_en = 'Rey Perun' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 329}'::jsonb WHERE name_en = 'Dodotto Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 330}'::jsonb WHERE name_en = 'Bariguiro' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 331}'::jsonb WHERE name_en = 'Glacial Bagpipe' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 332}'::jsonb WHERE name_en = 'Icespiel' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 333}'::jsonb WHERE name_en = 'Vicello Nulo Black' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 334}'::jsonb WHERE name_en = 'Veldian Sibilus' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 335}'::jsonb WHERE name_en = 'Duke''s Grail' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 336}'::jsonb WHERE name_en = 'Azure Elder Horn' AND type = 'horn';
UPDATE equipment SET stats = stats || '{"sort_id": 400}'::jsonb WHERE name_en = 'Iron Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 401}'::jsonb WHERE name_en = 'Felyne Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 402}'::jsonb WHERE name_en = 'Arzuros Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 403}'::jsonb WHERE name_en = 'Dawn Ray Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 404}'::jsonb WHERE name_en = 'Golm Bone Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 405}'::jsonb WHERE name_en = 'Crow Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 406}'::jsonb WHERE name_en = 'Hidden Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 407}'::jsonb WHERE name_en = 'Diablos Coilbender' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 408}'::jsonb WHERE name_en = 'Tigrex Archer' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 409}'::jsonb WHERE name_en = 'Sinister Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 410}'::jsonb WHERE name_en = 'Dragon Bow Solar' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 411}'::jsonb WHERE name_en = 'Kut-Ku Stave' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 412}'::jsonb WHERE name_en = 'Arko Nulo Red' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 413}'::jsonb WHERE name_en = 'Flammenbogen' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 414}'::jsonb WHERE name_en = 'Weaver of Flame' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 415}'::jsonb WHERE name_en = 'Dark Filament' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 416}'::jsonb WHERE name_en = 'Ashen Wrath' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 417}'::jsonb WHERE name_en = 'Seahorse Harp' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 418}'::jsonb WHERE name_en = 'Spongia Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 419}'::jsonb WHERE name_en = 'Blue Blade Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 420}'::jsonb WHERE name_en = 'Type 64 Multibow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 421}'::jsonb WHERE name_en = 'Mud Shot' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 422}'::jsonb WHERE name_en = 'Hydra Planula' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 423}'::jsonb WHERE name_en = 'Arko Nulo Yellow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 424}'::jsonb WHERE name_en = 'Kadachi Strikebow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 425}'::jsonb WHERE name_en = 'Lightning Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 426}'::jsonb WHERE name_en = 'Usurper''s Rumble' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 427}'::jsonb WHERE name_en = 'Rey Perkonis' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 428}'::jsonb WHERE name_en = 'Thunderbolt Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 429}'::jsonb WHERE name_en = 'Crystalline Flower' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 430}'::jsonb WHERE name_en = 'Arko Nulo White' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 431}'::jsonb WHERE name_en = 'Glacial Arrow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 432}'::jsonb WHERE name_en = 'Iceflinger' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 433}'::jsonb WHERE name_en = 'Arko Nulo Black' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 434}'::jsonb WHERE name_en = 'Insurgent''s Bow' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 435}'::jsonb WHERE name_en = 'Veldian Arcum' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 436}'::jsonb WHERE name_en = 'Duke''s Bloodwings' AND type = 'bow';
UPDATE equipment SET stats = stats || '{"sort_id": 500}'::jsonb WHERE name_en = 'Iron Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 501}'::jsonb WHERE name_en = 'Hard Hitter' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 502}'::jsonb WHERE name_en = 'Pukei Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 503}'::jsonb WHERE name_en = 'Barroth Loader' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 504}'::jsonb WHERE name_en = 'Shell Gunbird' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 505}'::jsonb WHERE name_en = 'Fiore Nulo Green' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 506}'::jsonb WHERE name_en = 'Cornpopper' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 507}'::jsonb WHERE name_en = 'Tiger Blast' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 508}'::jsonb WHERE name_en = 'Sinister Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 509}'::jsonb WHERE name_en = 'Gold Dragonwood Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 510}'::jsonb WHERE name_en = 'Fiore Nulo Red' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 511}'::jsonb WHERE name_en = 'Aknosom Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 512}'::jsonb WHERE name_en = 'Princess Panoply' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 513}'::jsonb WHERE name_en = 'Dios Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 514}'::jsonb WHERE name_en = 'Ajara Gunpike' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 515}'::jsonb WHERE name_en = 'Rosenkanone' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 516}'::jsonb WHERE name_en = 'White Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 517}'::jsonb WHERE name_en = 'Ludroth Harpoon' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 518}'::jsonb WHERE name_en = 'Type 62 Stormlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 519}'::jsonb WHERE name_en = 'Almudron Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 520}'::jsonb WHERE name_en = 'Marine Fisher' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 521}'::jsonb WHERE name_en = 'Hydra Ephyra' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 522}'::jsonb WHERE name_en = 'Kadachi Striker' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 523}'::jsonb WHERE name_en = 'Red Generator' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 524}'::jsonb WHERE name_en = 'Usurper''s Roar' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 525}'::jsonb WHERE name_en = 'Lagia Burst' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 526}'::jsonb WHERE name_en = 'Kamak Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 527}'::jsonb WHERE name_en = 'Hellsting' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 528}'::jsonb WHERE name_en = 'Twinfang' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 529}'::jsonb WHERE name_en = 'Frostmoon Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 530}'::jsonb WHERE name_en = 'Fiore Nulo Black' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 531}'::jsonb WHERE name_en = 'Ravenous Gunlance' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 532}'::jsonb WHERE name_en = 'Veldian Hasta' AND type = 'gunlance';
UPDATE equipment SET stats = stats || '{"sort_id": 0}'::jsonb WHERE name_en = 'Ranger Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 1}'::jsonb WHERE name_en = 'Hunter Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 2}'::jsonb WHERE name_en = 'Bone Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 3}'::jsonb WHERE name_en = 'Leather Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 4}'::jsonb WHERE name_en = 'Bnahabra Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 5}'::jsonb WHERE name_en = 'Lumu Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 6}'::jsonb WHERE name_en = 'Chatacabra Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 7}'::jsonb WHERE name_en = 'Kut-Ku Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 8}'::jsonb WHERE name_en = 'Kut-Ku U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 9}'::jsonb WHERE name_en = 'Gypceros Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 10}'::jsonb WHERE name_en = 'Gypceros U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 11}'::jsonb WHERE name_en = 'Ludroth Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 12}'::jsonb WHERE name_en = 'Ludroth U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 13}'::jsonb WHERE name_en = 'Nerscylla Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 14}'::jsonb WHERE name_en = 'Nerscylla U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 15}'::jsonb WHERE name_en = 'Kadachi Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 16}'::jsonb WHERE name_en = 'Plesioth Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 17}'::jsonb WHERE name_en = 'Plesioth U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 18}'::jsonb WHERE name_en = 'Anja Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 19}'::jsonb WHERE name_en = 'Fulgur Anja Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 20}'::jsonb WHERE name_en = 'Brachydios Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 21}'::jsonb WHERE name_en = 'Espinas Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 22}'::jsonb WHERE name_en = 'Rathian Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 23}'::jsonb WHERE name_en = 'Rath Heart Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 24}'::jsonb WHERE name_en = 'Lagiacrus Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 25}'::jsonb WHERE name_en = 'Lagiacrus U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 26}'::jsonb WHERE name_en = 'Astalos Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 27}'::jsonb WHERE name_en = 'Alloy Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 28}'::jsonb WHERE name_en = 'Edel Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 29}'::jsonb WHERE name_en = 'Yukumo Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 30}'::jsonb WHERE name_en = 'Izuchi Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 31}'::jsonb WHERE name_en = 'Arzuros Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 32}'::jsonb WHERE name_en = 'Tetranadon Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 33}'::jsonb WHERE name_en = 'Bishaten Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 34}'::jsonb WHERE name_en = 'Bishaten U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 35}'::jsonb WHERE name_en = 'Pukei-Pukei Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 36}'::jsonb WHERE name_en = 'Somnacanth Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 37}'::jsonb WHERE name_en = 'Somnacanth U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 38}'::jsonb WHERE name_en = 'Aknosom Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 39}'::jsonb WHERE name_en = 'Khezu Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 40}'::jsonb WHERE name_en = 'Khezu U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 41}'::jsonb WHERE name_en = 'Garuga Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 42}'::jsonb WHERE name_en = 'Golm Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 43}'::jsonb WHERE name_en = 'Regios Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 44}'::jsonb WHERE name_en = 'Vangis Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 45}'::jsonb WHERE name_en = 'Nargacuga Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 46}'::jsonb WHERE name_en = 'Nargacuga U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 47}'::jsonb WHERE name_en = 'Mizutsune Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 48}'::jsonb WHERE name_en = 'Azure Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 49}'::jsonb WHERE name_en = 'Guardian Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 50}'::jsonb WHERE name_en = 'Aelucanth Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 51}'::jsonb WHERE name_en = 'Rhopessa Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 52}'::jsonb WHERE name_en = 'Kululu Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 53}'::jsonb WHERE name_en = 'Barroth Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 54}'::jsonb WHERE name_en = 'Barroth U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 55}'::jsonb WHERE name_en = 'Ceanataur Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 56}'::jsonb WHERE name_en = 'Almudron Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 57}'::jsonb WHERE name_en = 'Ajarakan Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 58}'::jsonb WHERE name_en = 'Odogaron Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 59}'::jsonb WHERE name_en = 'Death Garon Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 60}'::jsonb WHERE name_en = 'Rakna Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 61}'::jsonb WHERE name_en = 'Glavenus Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 62}'::jsonb WHERE name_en = 'Diablos Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 63}'::jsonb WHERE name_en = 'Diablos Nero Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 64}'::jsonb WHERE name_en = 'Gravios Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 65}'::jsonb WHERE name_en = 'Gravios U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 66}'::jsonb WHERE name_en = 'Rey Dau Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 67}'::jsonb WHERE name_en = 'Tigrex Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 68}'::jsonb WHERE name_en = 'Tigrex U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 69}'::jsonb WHERE name_en = 'Zinogre Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 70}'::jsonb WHERE name_en = 'Zinogre U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 71}'::jsonb WHERE name_en = 'Artian Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 72}'::jsonb WHERE name_en = 'High Metal Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 73}'::jsonb WHERE name_en = 'Blango Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 74}'::jsonb WHERE name_en = 'Legiana Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 75}'::jsonb WHERE name_en = 'Goss Harag Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 76}'::jsonb WHERE name_en = 'Lunagaron Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 77}'::jsonb WHERE name_en = 'Rathalos Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 78}'::jsonb WHERE name_en = 'Rath Soul Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 79}'::jsonb WHERE name_en = 'Sinister Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 80}'::jsonb WHERE name_en = 'Arkvulcan Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 81}'::jsonb WHERE name_en = 'Barioth Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 82}'::jsonb WHERE name_en = 'Barioth U Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 83}'::jsonb WHERE name_en = 'Damascus Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 84}'::jsonb WHERE name_en = 'Malzeno Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 85}'::jsonb WHERE name_en = 'Tentacle Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 86}'::jsonb WHERE name_en = 'Rimeguard Armor' AND type = 'armor';
UPDATE equipment SET stats = stats || '{"sort_id": 0}'::jsonb WHERE name_en = 'Iron Sword' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 1}'::jsonb WHERE name_en = 'Cat''s Soul' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 2}'::jsonb WHERE name_en = 'Chrome Razor' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 3}'::jsonb WHERE name_en = 'Azure Serpentblade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 4}'::jsonb WHERE name_en = 'Scylla Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 5}'::jsonb WHERE name_en = 'Izuchi Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 6}'::jsonb WHERE name_en = 'Carapace Sword' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 7}'::jsonb WHERE name_en = 'Golm Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 8}'::jsonb WHERE name_en = 'Sentoryu Raven' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 9}'::jsonb WHERE name_en = 'Tiger Jawblade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 10}'::jsonb WHERE name_en = 'Cheda Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 11}'::jsonb WHERE name_en = 'Sinister Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 12}'::jsonb WHERE name_en = 'Chicken Decapitator' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 13}'::jsonb WHERE name_en = 'Aknosom Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 14}'::jsonb WHERE name_en = 'Valkyrie Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 15}'::jsonb WHERE name_en = 'Flammenzahn' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 16}'::jsonb WHERE name_en = 'Rosenbrett' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 17}'::jsonb WHERE name_en = 'Scorching Blazer' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 18}'::jsonb WHERE name_en = 'Rathalos Firesword' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 19}'::jsonb WHERE name_en = 'Tetranadon Edge' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 20}'::jsonb WHERE name_en = 'Ceanataur Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 21}'::jsonb WHERE name_en = 'Hanayako Yohino' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 22}'::jsonb WHERE name_en = 'Khezu Shock Sword' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 23}'::jsonb WHERE name_en = 'Donnerzahn' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 24}'::jsonb WHERE name_en = 'Lagiacrus Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 25}'::jsonb WHERE name_en = 'Frozen Speartuna' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 26}'::jsonb WHERE name_en = 'Gossblade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 27}'::jsonb WHERE name_en = 'Sword of Winter Moon' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 28}'::jsonb WHERE name_en = 'Epitaph Blade' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 29}'::jsonb WHERE name_en = 'Berserker Sword' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 30}'::jsonb WHERE name_en = 'Veldian Gladius' AND type = 'greatsword';
UPDATE equipment SET stats = stats || '{"sort_id": 31}'::jsonb WHERE name_en = 'Azure Elder Great Sword' AND type = 'greatsword';